#!/usr/bin/env bash
# quill-init.sh — first-time setup for a Docker deploy.
#
# Idempotent: re-running is safe; it only writes files that don't exist.
# Generates a bcrypt password hash + session secret using a throwaway
# container of the built image, so the host doesn't need bun/openssl.
#
# Usage:
#   ./scripts/quill-init.sh
#   docker compose up -d

set -euo pipefail

cd "$(dirname "$0")/.."

VAULT_DIR=${QUILL_VAULT_DIR:-./vault}
CONFIG_FILE=${QUILL_CONFIG_FILE:-./config.yaml}

mkdir -p "$VAULT_DIR"
echo "✓ vault dir ready at $VAULT_DIR"

if [ -f "$CONFIG_FILE" ]; then
  echo "✓ $CONFIG_FILE already exists — leaving as-is"
  exit 0
fi

# Build the image first so the hash-password helper runs inside it
# (one less host dependency).
if ! docker image inspect quill:latest >/dev/null 2>&1; then
  echo "→ building quill:latest (first time)…"
  docker compose build
fi

# Prompt for the access password. -s suppresses echo so terminal recordings
# don't leak the plaintext.
read -r -s -p "Set an access password: " PASSWORD
echo
if [ -z "$PASSWORD" ]; then
  echo "ERROR: password cannot be empty" >&2
  exit 1
fi

PASSWORD_HASH=$(docker run --rm -i quill:latest \
  bun run apps/server/scripts/hash-password.ts "$PASSWORD")

# 32 hex bytes = 256 bits; well above the 32-char minimum the config schema
# enforces. /dev/urandom is fine for HMAC keys.
SESSION_SECRET=$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')

cat > "$CONFIG_FILE" <<EOF
# Generated by scripts/quill-init.sh on $(date '+%Y-%m-%d %H:%M:%S %Z').
# Safe to edit by hand. To rotate the password, delete password_hash and
# re-run init; to rotate the session secret (invalidates all sessions),
# replace session_secret with a new 32+ char random string.

server:
  port: 3000

auth:
  password_hash: "$PASSWORD_HASH"
  session_secret: "$SESSION_SECRET"
  session_ttl_days: 30

vault:
  path: /data/vault

# Optional: enable AI agent. Uncomment + drop your api_key in. With the
# section absent, the web UI's AI panel hides itself rather than erroring.
#
# ai:
#   providers:
#     - id: openai
#       base_url: "https://api.openai.com/v1"
#       api_key: "\${OPENAI_API_KEY}"
#       models: ["gpt-4o-mini", "gpt-4o"]
EOF

chmod 600 "$CONFIG_FILE"
echo "✓ wrote $CONFIG_FILE (mode 600)"
echo
echo "Next:  docker compose up -d"
echo "Then:  open http://localhost:3000"
